### ISSUE TITLE
bytenode nestjs middleware Class constructor RequestContextMiddleware cannot be invoked without 'new'

### ISSUE THREAD

**Issue by SDAdham** [bytenode/bytenode#162]
Hello,

I have nestjs app that I am trying to use bytenode on it.

I was able to get the nestjs to start up and works perfectly, till a request is made then it gives the following error:

```
Class constructor RequestContextMiddleware cannot be invoked without 'new' - {"stack":[null]}
TypeError: Class constructor RequestContextMiddleware cannot be invoked without 'new'
    at Object.use (<proj-dir>/node_modules/@nestjs/core/middleware/utils.js:51:24)
    at <proj-dir>/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (<proj-dir>/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (<proj-dir>/node_modules/express/lib/router/index.js:317:13)
    at <proj-dir>/node_modules/express/lib/router/index.js:284:7
    at param (<proj-dir>/node_modules/express/lib/router/index.js:354:14)
    at param (<proj-dir>/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (<proj-dir>/node_modules/express/lib/router/index.js:410:3)
    at next (<proj-dir>/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (<proj-dir>/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (<proj-dir>/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (<proj-dir>/node_modules/express/lib/router/index.js:317:13)
    at <proj-dir>/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (<proj-dir>/node_modules/express/lib/router/index.js:335:12)
    at next (<proj-dir>/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (<proj-dir>/node_modules/body-parser/lib/types/json.js:110:7)
```

This works perfectly during development without bytenode in place. Can you please help?

**Comment by SDAdham** [comment]
See example code here https://docs.nestjs.com/middleware
```
consumer
      .apply(LoggerMiddleware)
      .forRoutes('cats');
```

**Comment by OsamaAbbas** [comment]
Please create a simple example that shows the error with clear steps.

**Comment by SDAdham** [comment]
Here is a simple project: https://github.com/SDAdham/bytenode-middleware-nestjs-bug

You will need to run `yarn install`

To reproduce (with the already packaged `dist` and `dist-bytenode`):

- `yarn start:bytenode`
- visit http://localhost:3002

To rebuild the output and test it from scratch

- delete `dist` and `dist-prod`
- `yarn build`
- `yarn bytenode:prod`
- `yarn start:bytenode`
- visit http://localhost:3002

What causes the issue:

- See [`app.module.ts:13`](https://github.com/SDAdham/bytenode-middleware-nestjs-bug/blob/07e7020b2ce4ab05126d1cbef44e988ae32dba36/src/app.module.ts#L13) where I tell nestjs that I want this middleware to kick-off on all requests
- What you would expect is that this [log line should run on every request and write to the console](https://github.com/SDAdham/bytenode-middleware-nestjs-bug/blob/07e7020b2ce4ab05126d1cbef44e988ae32dba36/src/test.middleware.ts#L6) instead, you would see the same error I get in the console and the browser will receive 5xx error

**Comment by OsamaAbbas** [comment]
Here is a workaround (thanks to @saucesteals in their #163 ticket):

add this line in your file: `src/test.middleware.ts`

```javascript
TestMiddleware.toString = () => "class TestMiddleware";
```

Recompile and it should work.
