### ISSUE TITLE
bytenode and (buffer or iconv) lead to set foreign_key_checks = 0; - Encoding not recognized: 'undefined' (searched as: 'undefined')

### ISSUE THREAD

**Issue by SDAdham** [bytenode/bytenode#165]
Hello Osama,

I am experiencing the following error:
```
previous Error: set foreign_key_checks = 0; - Encoding not recognized: 'undefined' (searched as: 'undefined')
    at Object.getCodec (/<proj-dir>/node_modules/mysql2/node_modules/iconv-lite/lib/index.js:104:23)
    at Object.getEncoder (/<proj-dir>/node_modules/mysql2/node_modules/iconv-lite/lib/index.js:115:23)
    at Object.encode (/<proj-dir>/node_modules/mysql2/lib/parsers/string.js:23:25)
    at Query.toPacket (/<proj-dir>/node_modules/mysql2/lib/packets/query.js:16:30)
    at Query.start (/<proj-dir>/node_modules/mysql2/lib/commands/query.js:60:38)
    at Query.execute (/<proj-dir>/node_modules/mysql2/lib/commands/command.js:45:22)
    at Connection.handlePacket (/<proj-dir>/node_modules/mysql2/lib/connection.js:456:32)
    at Connection.addCommand (/<proj-dir>/node_modules/mysql2/lib/connection.js:478:12)
    at Connection.query (/<proj-dir>/node_modules/mysql2/lib/connection.js:546:17)
    at /<proj-dir>/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL2._query (/<proj-dir>/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at Object.executeQuery (/<proj-dir>/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL2.<anonymous> (/<proj-dir>/node_modules/@mikro-orm/knex/dist/AbstractSqlConnection.js:169:71)
    at /<proj-dir>/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
```

Upon checking `node_modules/mysql2/lib/parsers/string.js:23:25`, I find it does the following:
```
if (Buffer.isEncoding(encoding)) {
    return Buffer.from(string, encoding);
  }

  const encoder = Iconv.getEncoder(encoding, options || {});
```
Where I found https://github.com/bytenode/bytenode/issues/10 and I also found another related issue https://stackoverflow.com/questions/46227783/encoding-not-recognized-in-jest-js

And so I added the following at the top of my starting up file `main.ts`:
```
global.Buffer = require('buffer').Buffer;
import iconv from 'iconv-lite';
import encodings from 'iconv-lite/encodings';
(iconv as any).encodings = encodings;
```
It didn't work, I am now changing it to:
```
var Buffer = require('buffer').Buffer;
import iconv from 'iconv-lite';
import encodings from 'iconv-lite/encodings';
(iconv as any).encodings = encodings;
```
Can you please let me know if I'm missing anything?

**Comment by SDAdham** [comment]
Also below didn't work
```
var Buffer = require('buffer').Buffer;
import iconv from 'iconv-lite';
import encodings from 'iconv-lite/encodings';
(iconv as any).encodings = encodings;
```

**Comment by OsamaAbbas** [comment]
Have you tried any of the workarounds mentioned [here](https://github.com/sidorares/node-mysql2/issues/489)?

But again, without a specific example, there is very little that I can do. You can contact me by email if you can't create a minimal example and you can't reveal your private code.

**Comment by SDAdham** [comment]
Hi @OsamaAbbas ,

my apologies, i should've done more investigation before opening this issue. I did trace the error and i realized it's from a different library and it's got nothing to do with bytenode.

Thanks a lot for being active and helping here.
