### ISSUE TITLE
App error with electron-releases fork

### ISSUE THREAD

**Issue by matgott** [bytenode/bytenode#177]
Hi, I was able to compile my electron app but when I want to launch the .exe generated I receive this errors:

```
[2022-03-28 00:45:27.071] [error] Error: spawn C:\...\app\node_modules\.bin\electron ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-03-28 00:50:47.452] [error] Error: spawn C:\...\app\node_modules\.bin\electron ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-03-28 13:31:46.098] [error] Error: spawn C:\...\app\node_modules\.bin\electron ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at messageBox (node:electron/js2c/browser_init:53:4661)
    at Object.showMessageBoxSync (node:electron/js2c/browser_init:53:5668)
    at C:\Users\...\app\build\electron\menu.js:51:47
    at step (C:\Users\...\app\build\electron\menu.js:33:23)
[2022-03-28 13:32:37.572] [error] Error: spawn C:\...\app\node_modules\.bin\electron ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-03-28 13:33:17.152] [error] Error: spawn C:\...\app\node_modules\.bin\electron ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-03-28 13:53:13.324] [error] Error: spawn C:\...\app\node_modules\.bin\electron ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by OsamaAbbas** [comment]
I apologize that I missed this issue. This is the first time I notice it.

Please provide a minimal reproducible example that shows the same error, something that I can run by `npm install && npm start` to see what goes wrong. Also, make sure that your app runs without bytenode.
