### ISSUE TITLE
bytenode cli returns a success exit code even if unable to compile script

### ISSUE THREAD

**Issue by travispaul** [bytenode/bytenode#234]
We use bytenode in a CI process and noticed a syntax error in the logs but it didn't stop the pipeline as it exited with a status code of 0. It would be nice if bytenode exited non-zero in such cases.

We were not checking the syntax of the file in question as it was partially generated, we're doing that now, so we have a solution but I figure I'd raise an issue here too. Thanks!

```
$ ./node_modules/.bin/bytenode -c test.js
evalmachine.<anonymous>:3
});
^

SyntaxError: Unexpected token '}'
    at new Script (node:vm:99:7)
    at compileCode (C:\src\project\node_modules\bytenode\lib\index.js:72:18)
    at Object.compileFile (C:\src\project\node_modules\bytenode\lib\index.js:268:22)
    at C:\src\project\node_modules\bytenode\lib\cli.js:118:24
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\src\project\node_modules\bytenode\lib\cli.js:110:17)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)

$ echo $?
0
```

**Comment by OsamaAbbas** [comment]
Yes, you are right. It should return 1 just like `gcc` would return 1 when it fails to compile.

I will fix it in the next version, hopefully soon (as we need to update bytenode anyways to support the latest Node.js version).
