### ISSUE TITLE
Invalid or incompatible cached data (cachedDataRejected) / PKG

### ISSUE THREAD

**Issue by gorgdel** [bytenode/bytenode#238]
I am trying to compile using PKG and bytenode.

I originally was accessing the file using the loader

```
require('bytenode')
module.exports = require('./bulk-replay.jsc')

```

However, when I try to spawn

```
replayer = fork(__dirname + "/FireBoardApp/backend/bytenode/core/replayWrapper.js");
```

I am getting decompression failed.

So I changed my method to trick PKG into not compiling the JSC.

```
const Module = require('module');
const bytenode = require('bytenode');
const path = require('path');

// Construct the module name
let moduleName = __dirname + '/bulk-replay.jsc';
// Resolve the full path to ensure correct module resolution
let modulePath = path.resolve(moduleName);

// Use Module._load to dynamically load the module
let loadedModule = Module._load(modulePath, module, false);
```
When trying to fork this, I get the error
```
Error: Invalid or incompatible cached data (cachedDataRejected)
    at generateScript (C:\snapshot\twinkruntboard2.0\node_modules\bytenode\lib\index.js:44:11)
    at runBytecode (C:\snapshot\twinkruntboard2.0\node_modules\bytenode\lib\index.js:200:18)
    at Object.runBytecodeFile (C:\snapshot\twinkruntboard2.0\node_modules\bytenode\lib\index.js:292:10)
    at Object.<anonymous> (C:\snapshot\twinkruntboard2.0\FireBoardApp\backend\bytenode\core\replayWrapper.js:2:21)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47.
 ```
    
   Is this due to the fact it was compiled before PKG and I should aim to compile it within the PKG environment, then remove the source files?

**Comment by OsamaAbbas** [comment]
I apologize for the late response. I thought I replied to this issue.

> 
I am trying to compile using PKG and bytenode.

I originally was accessing the file using the loader

require('bytenode')
module.exports = require('./bulk-replay.jsc')

However, when I try to spawn

replayer = fork(__dirname + "/FireBoardApp/backend/bytenode/core/replayWrapper.js");
I am getting decompression failed.

So I changed my method to trick PKG into not compiling the JSC.

const Module = require('module');
const bytenode = require('bytenode');
const path = require('path');

// Construct the module name
let moduleName = __dirname + '/bulk-replay.jsc';
// Resolve the full path to ensure correct module resolution
let modulePath = path.resolve(moduleName);

// Use Module._load to dynamically load the module
let loadedModule = Module._load(modulePath, module, false);
When trying to fork this, I get the error

Error: Invalid or incompatible cached data (cachedDataRejected)
    at generateScript (C:\snapshot\twinkruntboard2.0\node_modules\bytenode\lib\index.js:44:11)
    at runBytecode (C:\snapshot\twinkruntboard2.0\node_modules\bytenode\lib\index.js:200:18)
    at Object.runBytecodeFile (C:\snapshot\twinkruntboard2.0\node_modules\bytenode\lib\index.js:292:10)
    at Object.<anonymous> (C:\snapshot\twinkruntboard2.0\FireBoardApp\backend\bytenode\core\replayWrapper.js:2:21)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47.
Is this due to the fact it was compiled before PKG and I should aim to compile it within the PKG environment, then remove the source files?

Yes. Either this or try to compile using the same binary that PKG uses to run the project.
